### ISSUE TITLE
Instructions on Configurating Azure AD Permissions

### ISSUE THREAD

**Issue by ion-storm** [counteractive/o365beat#1]
I am attempting to get this working however I keep getting error parsing registry file, may not exist. errors even after specifying this location, what content do I need to store in here?  Also do you have additional instructions for pulling the api?
I followed the nxlog directions from here: https://nxlog.co/documentation/nxlog-user-guide/addon-msazure.html
And I get auth errors so far.

**Comment by chris-counteractive** [comment]
Thank you for the feedback.  I've updated the README with much more detailed instructions and links, including to Microsoft's [section on permissions](https://docs.microsoft.com/en-us/office/office-365-management-api/get-started-with-office-365-management-apis#specify-the-permissions-your-app-requires-to-access-the-office-365-management-apis).  Please let me know if that helps resolve your issues.

As for the errors parsing the registry file, I'd need a little more detail on your setup and the specific error: are you using the v1.1.0-alpha release?  What platform?  What's your config and command line look like?  

The default is to store the registry file in the location from which you run the binary or the path you specify in the `O365BEAT_REGISTRY_PATH` environment variable (`registry_file_path: ${O365BEAT_REGISTRY_PATH:./o365beat-registry.json}`).  I hope this helps, thanks again.
