### ISSUE TITLE
o365beat-registry.json?

### ISSUE THREAD

**Issue by awataszko** [counteractive/o365beat#2]
Hi,

What am I supposed to put for registry_file_path: ${O365BEAT_REGISTRY_PATH:./o365beat-registry.json}?

Thanks,
Andrew

**Comment by chris-counteractive** [comment]
We discussed the purpose of the `registry_file_path` setting a bit in [this comment thread](https://discuss.elastic.co/t/o365beat-v1-2-0-released-office-365-log-shipper/197985) on the Elastic discussion boards.  From that thread, for anyone reading this here:  "the `o365beat-registry.json` file is just the registry keeping track of the state of the downloads from the API to prevent repeatedly downloading the same events. If you look at the code you'll see it's just a date right now, the latest content blob retrieved."

Per your feedback, I updated the README to describe this setting (see https://github.com/counteractive/o365beat/commit/3b8e38bc71cd99949282ec5caba71329e57bcb07) and now provide a more helpful message when it's not found.

To answer your specific question, you can put the registry file wherever you want.  The default is the current working directory (everything after the `:` in the snippet you posted in this issue), but if you'd prefer to put it in `/etc/o365beat/` or somewhere else convenient, it won't affect the beat.  The main use is to know where to look if you want to delete the state (e.g., to re-download previously downloaded events).  Hope this helps, marking this issue closed.  Thanks for the question!
