### ISSUE TITLE
Response body not printed for authentication errors which hinders debugging.

### ISSUE THREAD

**Issue by chris-counteractive** [counteractive/o365beat#21]
Debugging and error information for authentication issues should be just as verbose as during API calls.  The most common error during auth is an incorrect client secret, but the current debugging output won't show those details, it just says `ERROR   instance/beat.go:877    Exiting: non-200 status during auth.` and the response object, but not the response _body_ which has the good stuff in it.

Fix is to match the [API call debug message](https://github.com/counteractive/o365beat/blob/master/beater/o365beat.go#L118-L119) and include the body.

**Comment by chris-counteractive** [comment]
The fix gives this output for incorrect client secret, for example, which should help when troubleshooting/debugging connection issues:

```text
Exiting: non-200 status during auth.
        check client secret and other config details.
        req: &{<request-object>}
        res: &{<response-object>}
        {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.<snip>}
```

**Comment by aymenwerg** [comment]
Hii chris, did you find a solution for this problem
I have the same Error

**Comment by chris-counteractive** [comment]
@aymenwerg - yes indeed, the versions since 4430cfc all print the authentication requests and responses.  I just replied to your email, if you email me your config file (`o365beat.yml`) and more of your error output (as much as you can provide), I should be able to help diagnose the issue.  Thanks!

**Comment by chris-counteractive** [comment]
@aymenwerg - the specific, most useful lines of the debugging output are the lines starting with `req` and `res` after the error message (`check client secret and other config details.`).  They can contain potentially sensitive info, so please send them via email.  Thanks!
