### ISSUE TITLE
Docker Instructions

### ISSUE THREAD

**Issue by BenB196** [counteractive/o365beat#40]
I would like to run this beat as a docker container, however I don't see any instructions for doing so. Is this something that is currently support?

**Comment by chris-counteractive** [comment]
Thanks @BenB196 for the issue, you're right that this is currently pretty anemic.  We haven't put any time into the Docker build target, but it's certainly on the roadmap.  I'll prioritize this for our next release and let you know when it's updated.

**Comment by aymenwerg** [comment]
@BenB196  if you run it as a docker container pls tell me 
I have many issue in my configuration

**Comment by SMAPPER** [comment]
If you want I have a docker build for this:

docker pull hasecuritysolutions/o365beat

The dockerfile is publicly available for viewing as well here:

https://github.com/HASecuritySolutions-Docker/o365beat/blob/master/Dockerfile

**Comment by chris-counteractive** [comment]
As filebeat [now supports o365 with an official module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-o365.html), as of v7.7.0, we recommend new users go with that solution.  Their [docker documentation](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html) is quite robust.  Thanks to @SMAPPER for the workaround, and @BenB196 for the long-standing issue!
